function validateSpatialDimensions( ...
    pulseqSize, productSize, pulseqFilename, productFilename)
%VALIDATESPATIALDIMENSIONS Confirm matching spatial matrix dimensions.

pulseqSize = padSize(pulseqSize, 3);
productSize = padSize(productSize, 3);

if ~isequal(pulseqSize(1:3), productSize(1:3))
    error('validateSpatialDimensions:SizeMismatch', ...
        ['Spatial dimensions do not match.\n' ...
         'Pulseq:  %s [%s]\n' ...
         'Product: %s [%s]'], ...
        pulseqFilename, ...
        num2str(pulseqSize(1:3)), ...
        productFilename, ...
        num2str(productSize(1:3)));
end

end
